---
title: "Introduction to PiPi"
author: "Pál Susánszky and Gergely Tóth"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(PiPi)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


Load example data and create `geginiData` objects.

```{r}
data(sam.data)
data <- geginiData(srvData=sam.data, cmpVar='cntry', ineqVar='vote', groupingVars='edu', naomit=TRUE) 
```

TODO

```{r}
PiPi.Min<- NULL
PiPi.Max<- NULL
PiPi.Mean<- NULL

for (i in 1:4){
  dta	<- data[[levels(sam.data$cntry)[i]]]
  bags<- NULL
  bags <- PiPiBagging(dta, ns=100, .progress = FALSE)
  PiPi.Min<- c(PiPi.Min, bags$PiPi.CI_lower) 
  PiPi.Max<- c(PiPi.Max, bags$PiPi.CI_upper) 
  PiPi.Mean<- c(PiPi.Mean, bags$PiPi.mean)
}
```

TODO

```{r}
tafel<- data.frame(PiPi.Min = PiPi.Min,
  PiPi.Max = PiPi.Max,
  PiPi.Mean = PiPi.Mean)

tafel
```

TODO

```{r}
dta <- data[[levels(sam.data$cntry)[4]]]
gegini(dta[[1]])
PiPi(dta)
```

TODO

```{r}
testV <- PiPi.Test(dta, ns=100, .progress = FALSE)
testV$PiPi0.CI_upper 	# random CI - upper limit
testV$PiPiOriginal$PiPi # observed value in the data
```

TODO

```{r}
bag1 <- PiPiBagging(dta, ns=100, .progress = FALSE)
dta2 <- data[[levels(sam.data$cntry)[2]]]
bag2 <- PiPiBagging(dta, ns=100, .progress = FALSE)
PiPibags.Test(bag1, bag2)
PiPibags.Test(bag1, bag2, alternative='greater')
```
